package com.plj.dao.admin.sys;

import org.springframework.stereotype.Repository;

import com.plj.dao.common.BaseDao;
import com.plj.domain.base.admin.sys.BaseRole;
import com.plj.domain.decorate.admin.sys.Role;

@Repository
public interface RoleDao extends BaseDao<Role>
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_t
     *
     * @mbggenerated
     */
    int insert(BaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_t
     *
     * @mbggenerated
     */
    int insertSelective(BaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_t
     *
     * @mbggenerated
     */
    BaseRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseRole record);
}