package com.plj.dao.admin.sys;

import org.springframework.stereotype.Repository;

import com.plj.dao.common.BaseDao;
import com.plj.domain.base.admin.sys.BaseUserLoginError;

@Repository
public interface UserLoginErrorDao extends BaseDao<LinkageError> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_login_error_t
     *
     * @mbggenerated
     */
    int insert(BaseUserLoginError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_login_error_t
     *
     * @mbggenerated
     */
    int insertSelective(BaseUserLoginError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_login_error_t
     *
     * @mbggenerated
     */
    BaseUserLoginError selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_login_error_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseUserLoginError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_login_error_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseUserLoginError record);
}