package com.plj.dao.admin.sys;

import org.springframework.stereotype.Repository;

import com.plj.dao.common.BaseDao;
import com.plj.domain.base.admin.sys.BaseUserRole;
import com.plj.domain.decorate.admin.sys.UserRole;

@Repository
public interface UserRoleDao extends BaseDao<UserRole>
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_m
     *
     * @mbggenerated
     */
    int insert(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_m
     *
     * @mbggenerated
     */
    int insertSelective(BaseUserRole record);
}