package com.plj.dao.admin.sys;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.plj.dao.common.BaseDao;
import com.plj.domain.base.admin.sys.BaseUser;
import com.plj.domain.decorate.admin.sys.User;

@Repository
public interface UserDao extends BaseDao<User>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_t
     *
     * @mbggenerated
     */
    int insert(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_t
     *
     * @mbggenerated
     */
    int insertSelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_t
     *
     * @mbggenerated
     */
    BaseUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseUser record);
    
    public User loadUserByName(@Param("username") String username);
}