package com.plj.domain.base.admin.sys;

import java.util.Date;

public class BaseUserLoginIp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_ip_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_ip_t.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_ip_t.login_ip
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_ip_t.login_count
     *
     * @mbggenerated
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_ip_t.logint_time
     *
     * @mbggenerated
     */
    private Date logintTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_ip_t.id
     *
     * @return the value of sys_user_login_ip_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_ip_t.id
     *
     * @param id the value for sys_user_login_ip_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_ip_t.user_id
     *
     * @return the value of sys_user_login_ip_t.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_ip_t.user_id
     *
     * @param userId the value for sys_user_login_ip_t.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_ip_t.login_ip
     *
     * @return the value of sys_user_login_ip_t.login_ip
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_ip_t.login_ip
     *
     * @param loginIp the value for sys_user_login_ip_t.login_ip
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_ip_t.login_count
     *
     * @return the value of sys_user_login_ip_t.login_count
     *
     * @mbggenerated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_ip_t.login_count
     *
     * @param loginCount the value for sys_user_login_ip_t.login_count
     *
     * @mbggenerated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_ip_t.logint_time
     *
     * @return the value of sys_user_login_ip_t.logint_time
     *
     * @mbggenerated
     */
    public Date getLogintTime() {
        return logintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_ip_t.logint_time
     *
     * @param logintTime the value for sys_user_login_ip_t.logint_time
     *
     * @mbggenerated
     */
    public void setLogintTime(Date logintTime) {
        this.logintTime = logintTime;
    }
}