package com.plj.domain.base.admin.sys;

public class BaseUrlInfo {
    private Integer id;

    private String urlName;

    private Integer menuId;

    private String url;
    
    private String channel;
    
    private String matchType;
    
    private String authType;

    private String funcDesc;
    
    private Boolean isAccess;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_url_t.id
     *
     * @param id the value for sys_menu_url_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_url_t.url_name
     *
     * @return the value of sys_menu_url_t.url_name
     *
     * @mbggenerated
     */
    public String getUrlName() {
        return urlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_url_t.url_name
     *
     * @param urlName the value for sys_menu_url_t.url_name
     *
     * @mbggenerated
     */
    public void setUrlName(String urlName) {
        this.urlName = urlName == null ? null : urlName.trim();
    }

    public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getMatchType() {
		return matchType;
	}

	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	public String getAuthType() {
		return authType;
	}

	public void setAuthType(String authType) {
		this.authType = authType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_url_t.menu_id
     *
     * @return the value of sys_menu_url_t.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_url_t.menu_id
     *
     * @param menuId the value for sys_menu_url_t.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_url_t.url
     *
     * @return the value of sys_menu_url_t.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_url_t.url
     *
     * @param url the value for sys_menu_url_t.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_url_t.func_desc
     *
     * @return the value of sys_menu_url_t.func_desc
     *
     * @mbggenerated
     */
    public String getFuncDesc() {
        return funcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_url_t.func_desc
     *
     * @param funcDesc the value for sys_menu_url_t.func_desc
     *
     * @mbggenerated
     */
    public void setFuncDesc(String funcDesc) {
        this.funcDesc = funcDesc == null ? null : funcDesc.trim();
    }

	public Boolean getIsAccess() {
		return isAccess;
	}

	public void setIsAccess(Boolean isAccess) {
		this.isAccess = isAccess;
	}
}