package com.plj.domain.base.admin.sys;

public class BaseUserLoginError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_error_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_error_t.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_error_t.error_msg
     *
     * @mbggenerated
     */
    private String errorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_error_t.error_time
     *
     * @mbggenerated
     */
    private String errorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_error_t.error_count
     *
     * @mbggenerated
     */
    private Integer errorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_login_error_t.error_ip
     *
     * @mbggenerated
     */
    private String errorIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_error_t.id
     *
     * @return the value of sys_user_login_error_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_error_t.id
     *
     * @param id the value for sys_user_login_error_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_error_t.user_id
     *
     * @return the value of sys_user_login_error_t.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_error_t.user_id
     *
     * @param userId the value for sys_user_login_error_t.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_error_t.error_msg
     *
     * @return the value of sys_user_login_error_t.error_msg
     *
     * @mbggenerated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_error_t.error_msg
     *
     * @param errorMsg the value for sys_user_login_error_t.error_msg
     *
     * @mbggenerated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_error_t.error_time
     *
     * @return the value of sys_user_login_error_t.error_time
     *
     * @mbggenerated
     */
    public String getErrorTime() {
        return errorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_error_t.error_time
     *
     * @param errorTime the value for sys_user_login_error_t.error_time
     *
     * @mbggenerated
     */
    public void setErrorTime(String errorTime) {
        this.errorTime = errorTime == null ? null : errorTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_error_t.error_count
     *
     * @return the value of sys_user_login_error_t.error_count
     *
     * @mbggenerated
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_error_t.error_count
     *
     * @param errorCount the value for sys_user_login_error_t.error_count
     *
     * @mbggenerated
     */
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_login_error_t.error_ip
     *
     * @return the value of sys_user_login_error_t.error_ip
     *
     * @mbggenerated
     */
    public String getErrorIp() {
        return errorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_login_error_t.error_ip
     *
     * @param errorIp the value for sys_user_login_error_t.error_ip
     *
     * @mbggenerated
     */
    public void setErrorIp(String errorIp) {
        this.errorIp = errorIp == null ? null : errorIp.trim();
    }
}